language: node_js
sudo: required
node_js:
  - "6.1"
  - "5.11"
branches:
  only:
  - master
  - development
addons:
  apt:
    packages:
    - libpq-dev
    - libpq5
    - postgresql-client-common
    - postgresql-common
before_script:
  - npm install
script:
  - ./package.js
